# Generated by Django 4.1.7 on 2023-04-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.ForeignKey(blank=True, default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_App.leadstatus'),
        ),
    ]
