# Generated by Django 4.1.7 on 2023-03-22 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Crm_App.status'),
        ),
    ]
