# Generated by Django 4.1.7 on 2023-03-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0003_extendedusermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusermodel',
            name='branch',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='usertype',
            field=models.CharField(max_length=25),
        ),
    ]
