# Generated by Django 4.1.7 on 2023-03-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0004_alter_extendedusermodel_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
