# Generated by Django 4.1.7 on 2023-04-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0004_projectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='key',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
