# Generated by Django 4.1.7 on 2023-04-11 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0005_project_key_projectassignment_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectassignment',
            old_name='user',
            new_name='added_by',
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectasgnmntmodule', to='Crm_App.project'),
        ),
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=25, null=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('module_title', models.CharField(blank=True, max_length=100, null=True)),
                ('module_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1')], default='1', max_length=10)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectModuleuser', to='Crm_App.extendedusermodel')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectmodulelead', to='Crm_App.leads')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectmoduleprjct', to='Crm_App.project')),
            ],
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='Crm_App.projectmodule'),
        ),
    ]
