# Generated by Django 4.1.7 on 2023-03-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0005_extendedusermodel_is_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendedusermodel',
            old_name='is_email_verified',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='auth_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
