# Generated by Django 4.1.7 on 2023-04-11 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Crm_App', '0006_rename_user_projectassignment_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodule',
            name='added_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
