# Generated by Django 4.1.7 on 2023-03-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0007_district_interestrate_leadcategory_state_leads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='extendeduser',
            new_name='added_by',
        ),
    ]
