# Generated by Django 4.1.7 on 2023-04-11 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0007_projectmodule_added_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='added_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='module_assigned',
            field=models.ManyToManyField(blank=True, related_name='module_assigned', to='Crm_App.projectmodule'),
        ),
    ]
