# Generated by Django 4.1.7 on 2023-04-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0009_projectassignment_added_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='projectassignment',
            name='project_module',
        ),
    ]
