# Generated by Django 4.1.7 on 2023-04-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0010_remove_project_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectlead', to='Crm_App.leads'),
        ),
    ]
