# Generated by Django 4.1.7 on 2023-03-24 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0010_district_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_category',
            field=models.ForeignKey(blank=True, default='Fresh', null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_App.leadcategory'),
        ),
    ]
