# Generated by Django 4.1.7 on 2023-04-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0011_project_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nlead', to='Crm_App.leads'),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectasgnmntlead', to='Crm_App.leads'),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectmodulelead', to='Crm_App.leads'),
        ),
    ]
