# Generated by Django 4.1.7 on 2023-03-24 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Crm_App', '0013_city_alter_leads_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='added_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
