# Generated by Django 4.1.7 on 2023-04-12 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0013_project_lead_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lead_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_view', to='Crm_App.leadsview'),
        ),
        migrations.AlterField(
            model_name='templead',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_App.leads'),
        ),
    ]
