# Generated by Django 4.1.7 on 2023-03-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0014_leads_added_by_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_about_client', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='Crm_App.leads')),
            ],
        ),
    ]
