# Generated by Django 4.1.7 on 2023-03-27 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0015_leadsview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_title', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_description', models.TextField(blank=True, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_person_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('lead_generated_date', models.DateField()),
                ('next_follow_up_date', models.DateField()),
                ('min_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('max_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('notes_about_client', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_App.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_App.district')),
                ('interest_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_App.interestrate')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crm_App.leads')),
                ('lead_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_App.leadcategory')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_App.state')),
                ('status', models.ForeignKey(blank=True, default='Fresh', null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_App.leadstatus')),
            ],
        ),
    ]
