# Generated by Django 4.1.7 on 2023-04-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0015_remove_leads_notes_about_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='assign_globaly',
            field=models.ManyToManyField(blank=True, related_name='assign_globaly', to='Crm_App.extendedusermodel'),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_App.branch'),
        ),
    ]
