# Generated by Django 4.1.7 on 2023-04-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0016_projectassignment_assign_globaly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='assign_globaly',
        ),
        migrations.RemoveField(
            model_name='projectassignment',
            name='branch',
        ),
    ]
