# Generated by Django 4.1.7 on 2023-03-29 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0017_leadsview_temp_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsview',
            name='temp_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tleads', to='Crm_App.templead'),
        ),
    ]
