# Generated by Django 4.1.7 on 2023-03-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0019_leads_exit_lead_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='exit_lead_desc',
        ),
    ]
