# Generated by Django 4.1.7 on 2023-03-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0020_remove_leads_exit_lead_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=25, null=True)),
                ('notification_title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1')], default=0, max_length=25)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('notified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('table_link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
