# Generated by Django 4.1.7 on 2023-03-31 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0022_notification_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nlead', to='Crm_App.leads'),
        ),
    ]
