# Generated by Django 4.1.7 on 2023-04-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0022_extendedusermodel_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='branch',
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='branch',
            field=models.ManyToManyField(blank=True, related_name='branch', to='Crm_App.branch'),
        ),
    ]
