# Generated by Django 4.1.7 on 2023-04-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0023_alter_notification_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_App.leadstatus'),
        ),
        migrations.AddField(
            model_name='leads',
            name='added_by',
            field=models.ManyToManyField(blank=True, to='Crm_App.extendedusermodel'),
        ),
    ]
