# Generated by Django 4.1.7 on 2023-04-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0022_alter_extendedusermodel_branch'),
        ('Crm_App', '0025_remove_projectassignment_branch_and_more'),
    ]

    operations = [
    ]
