# Generated by Django 4.1.7 on 2023-04-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0026_merge_20230427_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='assign_globaly',
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='assign_globaly',
            field=models.ManyToManyField(blank=True, related_name='assign_globaly', to='Crm_App.extendedusermodel'),
        ),
    ]
