# Generated by Django 4.1.7 on 2023-05-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0027_remove_projectassignment_assign_globaly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='assign_globaly',
        ),
    ]
