# Generated by Django 4.1.7 on 2023-05-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_App', '0028_remove_projectassignment_assign_globaly'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='assign_globaly',
            field=models.ManyToManyField(blank=True, related_name='assign_globaly', to='Crm_App.extendedusermodel'),
        ),
    ]
